// src/init.js
import fs from "node:fs";
import path from "node:path";
import { createInterface } from "node:readline/promises";
import { execa } from "execa";
import { c } from "./colors.js";

/* ------------------------------ helpers ----------------------------- */

function ensureDir(p) {
  if (!fs.existsSync(p)) fs.mkdirSync(p, { recursive: true });
}

async function getGitDirOrNull() {
  try {
    const { stdout } = await execa("git", ["rev-parse", "--git-dir"]);
    return stdout.trim();
  } catch {
    return null;
  }
}

async function setHooksPath(hooksPath) {
  await execa("git", ["config", "core.hooksPath", hooksPath]);
}

function writeFileIfNeeded(filePath, content, opts = {}) {
  const { force = false, mode } = opts;
  if (fs.existsSync(filePath) && !force) return "skipped";
  fs.writeFileSync(filePath, content, { encoding: "utf-8", mode });
  return fs.existsSync(filePath) ? "written" : "error";
}

function isWindows() {
  return process.platform === "win32";
}

function readPkgNameOrNull() {
  try {
    const raw = fs.readFileSync("package.json", "utf-8");
    const name = JSON.parse(raw)?.name;
    return typeof name === "string" ? name : null;
  } catch {
    return null;
  }
}

function sanitizeProjectKey(s) {
  return String(s ?? "")
    .trim()
    .toLowerCase()
    .replaceAll(/[^a-z0-9:_./-]+/g, "-")
    .replaceAll(/(?:^-+|-+$)/g, ""); // group the two alternatives explicitly
}

/* --------------------------- static templates ------------------------ */

const POSIX_HOOK = `#!/bin/sh
# Aegis pre-push (POSIX)
# Quiet by default; add --print-issues locally if you want console output
npx --no-install aegis run "$@"
status=$?
if [ $status -ne 0 ]; then
  echo "Aegis blocked push (Quality Gate failed). See saved issues file."
fi
exit $status
`;

const WIN_HOOK = `@echo off
REM Aegis pre-push (Windows)
npx --no-install aegis run %*
set EXITCODE=%ERRORLEVEL%
if NOT %EXITCODE%==0 (
  echo Aegis blocked push (Quality Gate failed). See saved issues file.
  exit /b %EXITCODE%
)
exit /b 0
`;

function sonarPropsTemplate({ host, key, name, sources, organization }) {
  const today = new Date().toISOString().slice(0, 10);
  const lines = [
    "# Generated by Aegis init on " + today,
    "# Adjust values as needed. SONAR_TOKEN must be set in your env.",
    "",
    `sonar.host.url=${host}`,
    `sonar.projectKey=${key}`,
    `sonar.projectName=${name}`,
  ];
  if (organization) lines.push(`sonar.organization=${organization}`);
  lines.push(
    `sonar.sources=${sources}`,
    "sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.next/**",
    "",
    "# Optional settings (uncomment if needed):",
    "# sonar.javascript.lcov.reportPaths=coverage/lcov.info",
    "# sonar.typescript.tsconfigPath=tsconfig.json",
    ""
  );
  return lines.join("\n");
}

function aegisRcTemplate() {
  // default issuesFile has no extension; run-time adds .md/.txt/.json
  return (
    JSON.stringify(
      {
        severities: "BLOCKER,CRITICAL,MAJOR",
        types: "BUG,VULNERABILITY,CODE_SMELL",
        max: 500,
        issuesFile: "sonar-issues",
        format: "md",
      },
      null,
      2
    ) + "\n"
  );
}

/* ---------------------------- small tasks ---------------------------- */

function normalizeLfAndChmod(posixPath) {
  try {
    const lf = fs.readFileSync(posixPath, "utf-8").replaceAll("\r\n", "\n");
    fs.writeFileSync(posixPath, lf, "utf-8");
  } catch {}
  try {
    if (!isWindows()) fs.chmodSync(posixPath, 0o755);
  } catch {}
}

function labelWriteResult(res) {
  if (res === "written") return c.ok("created");
  if (res === "skipped") return c.dim("exists (skipped)");
  return c.err("error");
}

/* ------------------------- scaffold sub-steps ------------------------- */

async function scaffoldHooks({ hooksPath, force }) {
  ensureDir(hooksPath);
  await setHooksPath(hooksPath);

  // show what Git sees now
  let effective = hooksPath;
  try {
    const { stdout } = await execa("git", ["config", "core.hooksPath"]);
    effective = (stdout || "").trim() || hooksPath;
  } catch {}

  console.log(c.ok("✔"), "hooksPath set to", c.dim(effective));

  const posixPath = path.join(hooksPath, "pre-push");
  const winPath = path.join(hooksPath, "pre-push.cmd");

  const posixRes = writeFileIfNeeded(posixPath, POSIX_HOOK, {
    force,
    mode: 0o755,
  });
  if (posixRes === "written") normalizeLfAndChmod(posixPath);

  const winRes = writeFileIfNeeded(winPath, WIN_HOOK, { force });

  console.log(
    c.info("• POSIX hook:"),
    c.dim(posixPath),
    "-",
    labelWriteResult(posixRes)
  );
  console.log(
    c.info("• Windows hook:"),
    c.dim(winPath),
    "-",
    labelWriteResult(winRes)
  );
}

function scaffoldSonarProps({
  force,
  hostFlag,
  keyFlag,
  nameFlag,
  sourcesFlag,
  organization = "",
}) {
  const sonarFile = "sonar-project.properties";
  const exists = fs.existsSync(sonarFile);

  if (exists && !force) {
    console.log(c.info("• sonar-project.properties:"), c.dim("exists (skipped)"));
    return "skipped";
  }

  const key     = keyFlag  || "your-project-id";
  const name    = nameFlag || keyFlag || "your-project-name";
  const host    = hostFlag || "https://your-sonarqube.example.com";
  const sources = sourcesFlag || ".";

  const content = sonarPropsTemplate({ host, key, name, sources, organization });
  const res = writeFileIfNeeded(sonarFile, content, { force });
  console.log(c.info("• sonar-project.properties:"), labelWriteResult(res));
  return res;
}

function scaffoldAegisRc() {
  const rcFile = ".aegisrc.json";
  if (fs.existsSync(rcFile)) {
    console.log(c.info("• .aegisrc.json:"), c.dim("exists (skipped)"));
    return "skipped";
  }
  const res = writeFileIfNeeded(rcFile, aegisRcTemplate(), { force: false });
  console.log(c.info("• .aegisrc.json:"), labelWriteResult(res));
  return res;
}

function finalHints({ didHooks, sonarStatus }) {
  console.log("");
  if (didHooks) {
    console.log(
      c.ok("✔"),
      "Aegis pre-push hook setup complete.",
      c.dim("(use --force to overwrite existing files)")
    );
  }
  if (sonarStatus === "written") {
    console.log(
      c.info("ℹ"),
      "Update",
      c.dim("sonar.host.url"),
      "and",
      c.dim("sonar.projectKey"),
      "if needed. Then export",
      c.dim("SONAR_TOKEN"),
      "before running:",
      c.dim("npx aegis run")
    );
  }
  console.log(
    c.info("ℹ"),
    "If your GUI doesn’t fire hooks, verify",
    c.dim("git config core.hooksPath"),
    "and presence of",
    c.dim("pre-push"),
    "and",
    c.dim("pre-push.cmd") + "."
  );
}

/* ----------------------------- gitignore ----------------------------- */

const GITIGNORE_ENTRIES = [
  "sonar-report.txt",
  "sonar-issues.txt",
  "sonar-issues.md",
  "sonar-issues.json",
  ".scannerwork/",
];

function updateGitignore() {
  const file = ".gitignore";
  const existing = fs.existsSync(file) ? fs.readFileSync(file, "utf-8") : "";
  const toAdd = GITIGNORE_ENTRIES.filter((e) => !existing.includes(e));
  if (toAdd.length === 0) {
    console.log(c.info("• .gitignore:"), c.dim("already up to date"));
    return;
  }
  const block = "\n# Aegis — generated files\n" + toAdd.join("\n") + "\n";
  fs.appendFileSync(file, block, "utf-8");
  console.log(c.info("• .gitignore:"), c.ok("updated"), c.dim("(+" + toAdd.join(", ") + ")"));
}

/* ------------------------------ wizard ------------------------------- */

async function ask(rl, question, defaultVal = "") {
  const hint = defaultVal ? c.dim(" [" + defaultVal + "]") : "";
  const raw = await rl.question(question + hint + ": ");
  return raw.trim() || defaultVal;
}

async function validateConnection(host, projectKey, token) {
  try {
    const url = host.replace(/\/$/, "") + "/api/components/show?component=" + encodeURIComponent(projectKey);
    const resp = await fetch(url, {
      headers: { Authorization: "Basic " + Buffer.from(token + ":").toString("base64") },
    });
    if (resp.status === 401) return { ok: false, reason: "token is invalid or expired" };
    if (resp.status === 403) return { ok: false, reason: "token lacks Browse permission on this project" };
    if (resp.status === 404) return { ok: false, reason: "project key not found on this server" };
    if (!resp.ok)            return { ok: false, reason: "server returned HTTP " + resp.status };
    return { ok: true };
  } catch (e) {
    return { ok: false, reason: "cannot reach server (" + (e?.message || e) + ")" };
  }
}

async function runWizard({ hooksPath, force }) {
  const rl = createInterface({ input: process.stdin, output: process.stdout });

  try {
    console.log(c.head("🔧 Aegis setup wizard"));
    console.log(c.dim("Press Enter to accept defaults shown in brackets.\n"));

    const existingProps = fs.existsSync("sonar-project.properties")
      ? (function () {
          const lines = fs.readFileSync("sonar-project.properties", "utf-8").split(/\r?\n/);
          const m = (k) => lines.find((l) => l.startsWith(k + "="))?.split("=")[1]?.trim() || "";
          return { host: m("sonar.host.url"), key: m("sonar.projectKey"), org: m("sonar.organization") };
        })()
      : { host: "", key: "", org: "" };

    const defaultHost = existingProps.host || "https://sonarcloud.io";
    const defaultKey  = existingProps.key  || readPkgNameOrNull() || "my-project";

    const host = await ask(rl, "SonarQube/SonarCloud host URL", defaultHost);
    const isSC = host.toLowerCase().includes("sonarcloud.io");
    let organization = "";
    if (isSC) {
      organization = await ask(rl, "SonarCloud organization slug", existingProps.org || "");
    }
    const projectKey = await ask(rl, "Project key", defaultKey);

    const envToken = process.env.SONAR_TOKEN || "";
    const tokenDefault = envToken ? "(using $SONAR_TOKEN)" : "";
    let token = envToken;
    if (!envToken) {
      token = await ask(rl, "SONAR_TOKEN (input hidden in terminal)", "");
    } else {
      console.log(c.info("ℹ"), "Using SONAR_TOKEN from environment.");
    }

    if (!token) {
      console.error(c.err("✖"), "SONAR_TOKEN is required.");
      process.exit(1);
    }

    // Live validation
    process.stdout.write(c.dim("  Validating connection…"));
    const result = await validateConnection(host, projectKey, token);
    process.stdout.write("\r" + " ".repeat(40) + "\r");
    if (result.ok) {
      console.log(c.ok("✔"), "Connection validated — project found.");
    } else {
      console.error(c.err("✖"), "Validation failed:", c.dim(result.reason));
      const cont = await ask(rl, "Continue anyway? (y/N)", "N");
      if (cont.toLowerCase() !== "y") process.exit(1);
    }

    return { host, projectKey, organization, isSC };
  } finally {
    rl.close();
  }
}

/* -------------------------------- init ------------------------------- */

export async function initHook(argv = {}) {
  const force = Boolean(argv.force);
  const scaffold = argv.scaffold !== false;
  const hooksPath = String(argv.hooksPath || ".githooks");

  const gitDir = await getGitDirOrNull();
  if (!gitDir) {
    console.error(c.err("✖"), "Not a Git repository or git not available on PATH.");
    process.exit(1);
  }

  // Sonar flags passed directly (non-interactive / scripted mode)
  const hostFlag     = argv.sonarHost || argv["sonar-host"] || "";
  const keyFlag      = argv.projectKey || argv["project-key"] || "";
  const nameFlag     = argv.projectName || argv["project-name"] || "";
  const sourcesFlag  = argv.sources || "";
  const hasFlags     = Boolean(hostFlag || keyFlag);

  // Run interactive wizard when in a TTY and no flags were provided
  const interactive = !hasFlags && process.stdin.isTTY && process.stdout.isTTY;

  let wizardResult = null;
  if (interactive) {
    wizardResult = await runWizard({ hooksPath, force });
    console.log("");
  } else {
    console.log(c.head("🔧 Aegis setup"));
  }

  // A) Hooks
  if (scaffold) {
    await scaffoldHooks({ hooksPath, force });
  } else {
    console.log(c.dim("Skipping hook scaffold (scaffold=false)."));
  }

  // B) sonar-project.properties (use wizard answers if available)
  const sonarStatus = scaffoldSonarProps({
    force: force || Boolean(wizardResult),
    hostFlag:    wizardResult?.host    || hostFlag,
    keyFlag:     wizardResult?.projectKey || keyFlag,
    nameFlag:    wizardResult ? wizardResult.projectKey : nameFlag,
    sourcesFlag,
    organization: wizardResult?.organization || "",
  });

  // C) .aegisrc.json
  scaffoldAegisRc();

  // D) .gitignore — always update
  updateGitignore();

  // E) Final hints
  finalHints({ didHooks: scaffold, sonarStatus });
}
